

GLOBALED_VALLEY_NPC_SPAWN_CHECK_INTERVAL = 15.0
--GLOBALED_VALLEY_NPC_SPAWN_TIME = 420.0 
--GLOBALED_VALLEY_NPC_SPAWN_TIME = 480.0 --
GLOBALED_VALLEY_NPC_SPAWN_TIME = 180.0 --
GLOBALED_VALLEY_NPC_WANDER_CHECK_INTERVAL = 3.0

--GLOBALED_VALLEY_NPC_WANDER_DISTANCE = 768.0
--GLOBALED_VALLEY_NPC_WANDER_DISTANCE_VERTICAL = 64.0

GLOBALED_VALLEY_NPC_WANDER_DISTANCE = 240.0
GLOBALED_VALLEY_NPC_WANDER_DISTANCE_VERTICAL = 0.0

GLOBALED_VALLEY_CHICKEN_REGEN_HEAL_PERCENTAGE = 0.0045

GLOBALED_VALLEY_NPC_WANDER_LEASH_RANGE = 100.0

GLOBALED_VALLEY_NPC_LEASH_RANGE = 3000.0


-- ranged scaling percent. 1.0 = 100% damage
GLOBALED_VALLEY_RANGED_UPTIME_TUNING_PERCENTAGE_FLOAT = 2.5
-- hero based uptime tuning. 1.0 = 100% uptime, 0.1 = 10% uptime
GLOBALED_VALLEY_NPC_DOTA_HERO_CRYSTAL_MAIDEN_EXPECTED_MELEE_ENEMY_UPTIME_IN_FLOAT = 0.2
GLOBALED_VALLEY_NPC_DOTA_HERO_BOUNTY_HUNTER_EXPECTED_MELEE_ENEMY_UPTIME_IN_FLOAT = 1.0
GLOBALED_VALLEY_NPC_DOTA_HERO_DROW_RANGER_EXPECTED_MELEE_ENEMY_UPTIME_IN_FLOAT = 0.2
GLOBALED_VALLEY_NPC_DOTA_HERO_ENCHANTRESS_EXPECTED_MELEE_ENEMY_UPTIME_IN_FLOAT = 1.0
GLOBALED_VALLEY_NPC_DOTA_HERO_NECROLYTE_EXPECTED_MELEE_ENEMY_UPTIME_IN_FLOAT = 0.65
GLOBALED_VALLEY_NPC_DOTA_HERO_OMNIKNIGHT_EXPECTED_MELEE_ENEMY_UPTIME_IN_FLOAT = 1.0
GLOBALED_VALLEY_NPC_DOTA_HERO_PHANTOM_ASSASSIN_EXPECTED_MELEE_ENEMY_UPTIME_IN_FLOAT = 1.0
GLOBALED_VALLEY_NPC_DOTA_HERO_STORM_SPIRIT_EXPECTED_MELEE_ENEMY_UPTIME_IN_FLOAT = 1.0
GLOBALED_VALLEY_NPC_DOTA_HERO_UNDYING_EXPECTED_MELEE_ENEMY_UPTIME_IN_FLOAT = 1.0
GLOBALED_VALLEY_NPC_DOTA_HERO_LINA_EXPECTED_MELEE_ENEMY_UPTIME_IN_FLOAT = 0.4

-- Starts nil, above variables are set to GLOBALED_VALLEY_NPC_UPTIME_SCALING_VARIABLE on function GameMode:OnHeroInGame(hero)
-- GLOBALED_VALLEY_NPC_UPTIME_SCALING_VARIABLE


-- items/drops/consumables
GLOBALED_VALLEY_CONSUMABLE_TANGO_CHANCE = 20

GLOBALED_VALLEY_QUEST_COMPLETION_DIALOG_LINGER_TIME = 60.0

-- npcs
GLOBALED_VALLEY_NPC_SOLO_EASY_WOLF_SECONDS_TO_KILL = 3.0
GLOBALED_VALLEY_NPC_SOLO_EASY_WOLF_DPS = 15

GLOBALED_VALLEY_NPC_SOLO_MELEE_CREEP_SECONDS_TO_KILL = 15.0
GLOBALED_VALLEY_NPC_SOLO_MELEE_CREEP_DPS = 10

GLOBALED_VALLEY_NPC_SOLO_RANGED_CREEP_SECONDS_TO_KILL = 12.0
GLOBALED_VALLEY_NPC_SOLO_RANGED_CREEP_DPS = 16

-- Quest one sithill kill wolves
GLOBALED_VALLEY_QUEST_ONE_WOLF_KILLS_REQUIRED = 5


